# Generated by Django 2.1 on 2019-01-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='用户名')),
                ('passwd', models.CharField(max_length=32, verbose_name='密码')),
                ('is_root', models.IntegerField(choices=[(0, '管理员'), (1, '普通用户')], default=1, verbose_name='角色')),
            ],
            options={
                'verbose_name': '用户',
            },
        ),
    ]
