# Generated by Django 2.1 on 2019-01-19 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名字')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'verbose_name': '作者',
            },
        ),
        migrations.CreateModel(
            name='AuthorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('telephone', models.CharField(max_length=32, verbose_name='电话号码')),
                ('addr', models.CharField(max_length=32, verbose_name='地址')),
            ],
            options={
                'verbose_name': '作者详情',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='书籍名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='价格')),
                ('pud_status', models.IntegerField(choices=[(0, '未出版'), (1, '已出版')], default=1, verbose_name='是否出版')),
                ('pub_date', models.DateField(verbose_name='出版日期')),
                ('authors', models.ManyToManyField(to='app01.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '书籍',
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='出版社')),
                ('addr', models.CharField(max_length=32, verbose_name='地址')),
                ('email', models.CharField(max_length=32, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '出版社',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Publish', verbose_name='出版社'),
        ),
        migrations.AddField(
            model_name='author',
            name='auhthorDetail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.AuthorDetail', verbose_name='作者详情'),
        ),
    ]
